CREATE OR ALTER FUNCTION FN_MONTO_VENTA
(@ID AS INT)
RETURNS DECIMAL (9,2)
AS
BEGIN
	DECLARE @MONTO_IND AS DECIMAL(9,2)=0.0
	DECLARE @MONTO_FINAL AS DECIMAL(9,2)=0.0
	DECLARE CURSOR_MONTOS CURSOR FOR 
	SELECT  (SELECT TOP 1 PRECIO_FINAL FROM PRECIOS_BOLETOS WHERE ID_PRECIO=BL.FK_PRECIO_BOLETO) FROM dbo.VENTAS VT
		JOIN dbo.BOLETOS BL ON  VT.ID_VENTA=BL.FK_VENTA
		--JOIN dbo.PRECIOS_BOLETOS  PB ON PB.ID_PRECIO=BL.FK_PRECIO_BOLETO
		WHERE BL.FK_VENTA=VT.ID_VENTA
		AND VT.ESTATUS_VENTA=1
		AND VT.ID_VENTA=@ID
	OPEN CURSOR_MONTOS FETCH CURSOR_MONTOS INTO @MONTO_IND
	WHILE @@FETCH_STATUS=0
	BEGIN
		SET @MONTO_FINAL=@MONTO_FINAL+@MONTO_IND
		FETCH CURSOR_MONTOS INTO @MONTO_IND
	END
	CLOSE CURSOR_MONTOS
	DEALLOCATE CURSOR_MONTOS
	
	RETURN @MONTO_FINAL
END
GO
